services:
  irav-server-prueba:
    build: .
    ports:
      - 8080:80
      - 8081:81
      - 20:20
      - 21:21
      - 40000-40100:40000-40100
    volumes:
      - './apache/public_html:/usr/local/apache2/htdocs/apache'
      - './node/public_html:/usr/local/apache2/htdocs/node'
      - './logs/supervisor:/var/log/supervisor'
